src/Entity/Patients.php
<?php

namespace App\Entity;

use App\Repository\PatientsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PatientsRepository::class)
 */
class Patients
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_patient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname_patient;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="date")
     */
    private $date_birth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $doctor;

    /**
     * @ORM\OneToOne(targetEntity=Payments::class, inversedBy="patients", cascade={"persist", "remove"})
     */
    private $payment_sum;

    /**
     * @ORM\OneToOne(targetEntity=Reports::class, inversedBy="patients", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $report_patient;

    /**
     * @ORM\OneToOne(targetEntity=Results::class, inversedBy="patients", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $result_patient;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="patients")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=AnalysisCategories::class, mappedBy="patients")
     */
    private $analysiscategorie;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="patients")
     */
    private $room;

    public function __construct()
    {
        $this->analysis_type = new ArrayCollection();
        $this->analysiscategorie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNamePatient(): ?string
    {
        return $this->name_patient;
    }

    public function setNamePatient(string $name_patient): self
    {
        $this->name_patient = $name_patient;

        return $this;
    }

    public function getFirstnamePatient(): ?string
    {
        return $this->firstname_patient;
    }

    public function setFirstnamePatient(string $firstname_patient): self
    {
        $this->firstname_patient = $firstname_patient;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeInterface
    {
        return $this->date_birth;
    }

    public function setDateBirth(\DateTimeInterface $date_birth): self
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getDoctor(): ?string
    {
        return $this->doctor;
    }

    public function setDoctor(string $doctor): self
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getPaymentSum(): ?Payments
    {
        return $this->payment_sum;
    }

    public function setPaymentSum(?Payments $payment_sum): self
    {
        $this->payment_sum = $payment_sum;

        return $this;
    }

    public function getReportPatient(): ?Reports
    {
        return $this->report_patient;
    }

    public function setReportPatient(Reports $report_patient): self
    {
        $this->report_patient = $report_patient;

        return $this;
    }

    public function getResultPatient(): ?Results
    {
        return $this->result_patient;
    }

    public function setResultPatient(Results $result_patient): self
    {
        $this->result_patient = $result_patient;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|AnalysisCategories[]
     */
    public function getAnalysiscategorie(): Collection
    {
        return $this->analysiscategorie;
    }

    public function addAnalysiscategorie(AnalysisCategories $analysiscategorie): self
    {
        if (!$this->analysiscategorie->contains($analysiscategorie)) {
            $this->analysiscategorie[] = $analysiscategorie;
            $analysiscategorie->setPatients($this);
        }

        return $this;
    }

    public function removeAnalysiscategorie(AnalysisCategories $analysiscategorie): self
    {
        if ($this->analysiscategorie->contains($analysiscategorie)) {
            $this->analysiscategorie->removeElement($analysiscategorie);
            // set the owning side to null (unless already changed)
            if ($analysiscategorie->getPatients() === $this) {
                $analysiscategorie->setPatients(null);
            }
        }

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }
}

src/Form/PatientsType.php
<?php

namespace App\Form;

use App\Entity\Patients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_patient')
            ->add('firstname_patient')
            ->add('phone')
            ->add('date_birth')
            ->add('doctor')
            ->add('payment_sum')
            ->add('report_patient')
            ->add('result_patient')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Patients::class,
        ]);
    }
}

src/Controller/PatientsController.php
<?php

namespace App\Controller;

use App\Entity\Patients;
use App\Form\PatientsType;
use App\Repository\PatientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/patients")
 */
class PatientsController extends AbstractController
{
    /**
     * @Route("/", name="patients_index", methods={"GET"})
     */
    public function index(PatientsRepository $patientsRepository): Response
    {
        return $this->render('patients/index.html.twig', [
            'patients' => $patientsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="patients_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $patient = new Patients();
        $form = $this->createForm(PatientsType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($patient);
            $entityManager->flush();

            return $this->redirectToRoute('patients_index');
        }

        return $this->render('patients/new.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="patients_show", methods={"GET"})
     */
    public function show(Patients $patient): Response
    {
        return $this->render('patients/show.html.twig', [
            'patient' => $patient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="patients_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Patients $patient): Response
    {
        $form = $this->createForm(PatientsType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('patients_index');
        }

        return $this->render('patients/edit.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="patients_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Patients $patient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$patient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($patient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('patients_index');
    }
}

templates/patients/_delete_form.html.twig
<form method="post" action="{{ path('patients_delete', {'id': patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/patients/edit.html.twig
{% extends 'users.index.html.twig' %}

{% block title %}Edit Patients{% endblock %}

{% block body %}
    <h1>Edit Patients</h1>

    {{ include('patients/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('patients_index') }}">back to list</a>

    {{ include('patients/_delete_form.html.twig') }}
{% endblock %}

templates/patients/index.html.twig
{% extends './users/index.html.twig' %}

{% block title %}Patients index{% endblock %}

{% block body %}
    <h1>Patients index</h1>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Name_patient</th>
                <th>Firstname_patient</th>
                <th>Phone</th>
                <th>Date_birth</th>
                <th>Doctor</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for patient in patients %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.namePatient }}</td>
                <td>{{ patient.firstnamePatient }}</td>
                <td>{{ patient.phone }}</td>
                <td>{{ patient.dateBirth ? patient.dateBirth|date('Y-m-d') : '' }}</td>
                <td>{{ patient.doctor }}</td>
                <td>
                    <a href="{{ path('patients_show', {'id': patient.id}) }}">show</a>
                    <a href="{{ path('patients_edit', {'id': patient.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('patients_new') }}">Create new</a>
{% endblock %}

templates/patients/new.html.twig
{% extends './users/index.html.twig' %}

{% block title %}New Patients{% endblock %}

{% block body %}
    <h1>Create new Patients</h1>

    {{ include('patients/_form.html.twig') }}

    <a href="{{ path('patients_index') }}">back to list</a>
{% endblock %}

templates/patients/show.html.twig
{% extends './users/index.html.twig' %}

{% block title %}Patients{% endblock %}

{% block body %}
    <h1>Patients</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ patient.id }}</td>
            </tr>
            <tr>
                <th>Name_patient</th>
                <td>{{ patient.namePatient }}</td>
            </tr>
            <tr>
                <th>Firstname_patient</th>
                <td>{{ patient.firstnamePatient }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ patient.phone }}</td>
            </tr>
            <tr>
                <th>Date_birth</th>
                <td>{{ patient.dateBirth ? patient.dateBirth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Doctor</th>
                <td>{{ patient.doctor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('patients_index') }}">back to list</a>

    <a href="{{ path('patients_edit', {'id': patient.id}) }}">edit</a>

    {{ include('patients/_delete_form.html.twig') }}
{% endblock %}