src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $availibityStatus;

    /**
     * @ORM\OneToMany(targetEntity=Patients::class, mappedBy="room")
     */
    private $patients;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_room;

    public function __construct()
    {
        $this->patients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAvailibityStatus(): ?bool
    {
        return $this->availibityStatus;
    }

    public function setAvailibityStatus(bool $availibityStatus): self
    {
        $this->availibityStatus = $availibityStatus;

        return $this;
    }

    /**
     * @return Collection|Patients[]
     */
    public function getPatients(): Collection
    {
        return $this->patients;
    }

    public function addPatient(Patients $patient): self
    {
        if (!$this->patients->contains($patient)) {
            $this->patients[] = $patient;
            $patient->setRoom($this);
        }

        return $this;
    }

    public function removePatient(Patients $patient): self
    {
        if ($this->patients->contains($patient)) {
            $this->patients->removeElement($patient);
            // set the owning side to null (unless already changed)
            if ($patient->getRoom() === $this) {
                $patient->setRoom(null);
            }
        }

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getNameRoom(): ?string
    {
        return $this->name_room;
    }

    public function setNameRoom(string $name_room): self
    {
        $this->name_room = $name_room;

        return $this;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('availibityStatus')
            ->add('name_room')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Form\RoomType;
use App\Repository\RoomRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     */
    public function index(RoomRepository $roomRepository): Response
    {
        return $this->render('room/index.html.twig', [
            'rooms' => $roomRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_show", methods={"GET"})
     */
    public function show(Room $room): Response
    {
        return $this->render('room/show.html.twig', [
            'room' => $room,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }
}

templates/room/_delete_form.html.twig
<form method="post" action="{{ path('room_delete', {'id': room.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
    <button class="btn">Delete</button>
</form>

templates/room/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Room{% endblock %}

{% block body %}
    <h1>Edit Room</h1>

    {{ include('room/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('room_index') }}">back to list</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Room index{% endblock %}

{% block body %}
    <h1>Room index</h1>

    <table class="table">
    <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>AvailibityStatus</th>
                <th>Name_room</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for room in rooms %}
            <tr>
                <td>{{ room.id }}</td>
                <td>{{ room.availibityStatus ? 'Yes' : 'No' }}</td>
                <td>{{ room.nameRoom }}</td>
                <td>
                    <a href="{{ path('room_show', {'id': room.id}) }}">show</a>
                    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('room_new') }}">Create new</a>
{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Room{% endblock %}

{% block body %}
    <h1>Create new Room</h1>

    {{ include('room/_form.html.twig') }}

    <a href="{{ path('room_index') }}">back to list</a>
{% endblock %}

templates/room/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Room{% endblock %}

{% block body %}
    <h1>Room</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ room.id }}</td>
            </tr>
            <tr>
                <th>AvailibityStatus</th>
                <td>{{ room.availibityStatus ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Name_room</th>
                <td>{{ room.nameRoom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('room_index') }}">back to list</a>

    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}