src/Entity/Payments.php
<?php

namespace App\Entity;

use App\Repository\PaymentsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaymentsRepository::class)
 */
class Payments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_payment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="integer")
     */
    private $sum;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content_payment;

    /**
     * @ORM\OneToOne(targetEntity=Patients::class, mappedBy="payment_sum", cascade={"persist", "remove"})
     */
    private $patients;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNamePayment(): ?string
    {
        return $this->name_payment;
    }

    public function setNamePayment(string $name_payment): self
    {
        $this->name_payment = $name_payment;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSum(): ?int
    {
        return $this->sum;
    }

    public function setSum(int $sum): self
    {
        $this->sum = $sum;

        return $this;
    }

    public function getContentPayment(): ?string
    {
        return $this->content_payment;
    }

    public function setContentPayment(string $content_payment): self
    {
        $this->content_payment = $content_payment;

        return $this;
    }

    public function getPatients(): ?Patients
    {
        return $this->patients;
    }

    public function setPatients(?Patients $patients): self
    {
        $this->patients = $patients;

        // set (or unset) the owning side of the relation if necessary
        $newPayment_sum = null === $patients ? null : $this;
        if ($patients->getPaymentSum() !== $newPayment_sum) {
            $patients->setPaymentSum($newPayment_sum);
        }

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

src/Form/PaymentsType.php
<?php

namespace App\Form;

use App\Entity\Payments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaymentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_payment')
            ->add('status')
            ->add('sum')
            ->add('content_payment')
            ->add('patients')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Payments::class,
        ]);
    }
}

src/Controller/PaymentsController.php
<?php

namespace App\Controller;

use App\Entity\Payments;
use App\Form\PaymentsType;
use App\Repository\PaymentsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/payments")
 */
class PaymentsController extends AbstractController
{
    /**
     * @Route("/", name="payments_index", methods={"GET"})
     */
    public function index(PaymentsRepository $paymentsRepository): Response
    {
        return $this->render('payments/index.html.twig', [
            'payments' => $paymentsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="payments_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $payment = new Payments();
        $form = $this->createForm(PaymentsType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($payment);
            $entityManager->flush();

            return $this->redirectToRoute('payments_index');
        }

        return $this->render('payments/new.html.twig', [
            'payment' => $payment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="payments_show", methods={"GET"})
     */
    public function show(Payments $payment): Response
    {
        return $this->render('payments/show.html.twig', [
            'payment' => $payment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="payments_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Payments $payment): Response
    {
        $form = $this->createForm(PaymentsType::class, $payment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('payments_index');
        }

        return $this->render('payments/edit.html.twig', [
            'payment' => $payment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="payments_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Payments $payment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$payment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($payment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('payments_index');
    }
}

templates/payments/_delete_form.html.twig
<form method="post" action="{{ path('payments_delete', {'id': payment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ payment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/payments/edit.html.twig
{% extends './users/index.html.twig' %}

{% block title %}Edit Payments{% endblock %}

{% block body %}
    <h1>Edit Payments</h1>

    {{ include('payments/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('payments_index') }}">back to list</a>

    {{ include('payments/_delete_form.html.twig') }}
{% endblock %}

templates/payments/index.html.twig
{% extends './users/index.html.twig' %}

{% block title %}Payments index{% endblock %}

{% block body %}
    <h1>Payments index</h1>

    <table class="table">
    <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Name_payment</th>
                <th>Status</th>
                <th>Sum</th>
                <th>Content_payment</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
            <tr>
                <td>{{ payment.id }}</td>
                <td>{{ payment.namePayment }}</td>
                <td>{{ payment.status ? 'Yes' : 'No' }}</td>
                <td>{{ payment.sum }}</td>
                <td>{{ payment.contentPayment }}</td>
                <td>
                    <a href="{{ path('payments_show', {'id': payment.id}) }}">show</a>
                    <a href="{{ path('payments_edit', {'id': payment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('payments_new') }}">Create new</a>
{% endblock %}

templates/payments/new.html.twig
{% extends './users/index.html.twig' %}

{% block title %}New Payments{% endblock %}

{% block body %}
    <h1>Create new Payments</h1>

    {{ include('payments/_form.html.twig') }}

    <a href="{{ path('payments_index') }}">back to list</a>
{% endblock %}

templates/payments/show.html.twig
{% extends './users/index.html.twig' %}

{% block title %}Payments{% endblock %}

{% block body %}
    <h1>Payments</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ payment.id }}</td>
            </tr>
            <tr>
                <th>Name_payment</th>
                <td>{{ payment.namePayment }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ payment.status ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Sum</th>
                <td>{{ payment.sum }}</td>
            </tr>
            <tr>
                <th>Content_payment</th>
                <td>{{ payment.contentPayment }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('payments_index') }}">back to list</a>

    <a href="{{ path('payments_edit', {'id': payment.id}) }}">edit</a>

    {{ include('payments/_delete_form.html.twig') }}
{% endblock %}