src/Entity/AnalysisType.php
<?php

namespace App\Entity;

use App\Repository\AnalysisTypeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnalysisTypeRepository::class)
 */
class AnalysisType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $analysis_name;

    /**
     * @ORM\ManyToOne(targetEntity=Patients::class, inversedBy="analysis_type")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patients;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="analysistypes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnalysisName(): ?string
    {
        return $this->analysis_name;
    }

    public function setAnalysisName(string $analysis_name): self
    {
        $this->analysis_name = $analysis_name;

        return $this;
    }

    public function getPatients(): ?Patients
    {
        return $this->patients;
    }

    public function setPatients(?Patients $patients): self
    {
        $this->patients = $patients;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

src/Form/AnalysisCategoriesType.php
<?php

namespace App\Form;

use App\Entity\AnalysisCategories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnalysisCategoriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('analysis_name')
            ->add('patients')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AnalysisCategories::class,
        ]);
    }
}

src/Controller/AnalysisCategoriesController.php
<?php

namespace App\Controller;

use App\Entity\AnalysisCategories;
use App\Form\AnalysisCategoriesType;
use App\Repository\AnalysisCategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/analysis/categories")
 */
class AnalysisCategoriesController extends AbstractController
{
    /**
     * @Route("/", name="analysis_categories_index", methods={"GET"})
     */
    public function index(AnalysisCategoriesRepository $analysisCategoriesRepository): Response
    {
        return $this->render('analysis_categories/index.html.twig', [
            'analysis_categories' => $analysisCategoriesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="analysis_categories_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $analysisCategory = new AnalysisCategories();
        $form = $this->createForm(AnalysisCategoriesType::class, $analysisCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($analysisCategory);
            $entityManager->flush();

            return $this->redirectToRoute('analysis_categories_index');
        }

        return $this->render('analysis_categories/new.html.twig', [
            'analysis_category' => $analysisCategory,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="analysis_categories_show", methods={"GET"})
     */
    public function show(AnalysisCategories $analysisCategory): Response
    {
        return $this->render('analysis_categories/show.html.twig', [
            'analysis_category' => $analysisCategory,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="analysis_categories_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AnalysisCategories $analysisCategory): Response
    {
        $form = $this->createForm(AnalysisCategoriesType::class, $analysisCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('analysis_categories_index');
        }

        return $this->render('analysis_categories/edit.html.twig', [
            'analysis_category' => $analysisCategory,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="analysis_categories_delete", methods={"DELETE"})
     */
    public function delete(Request $request, AnalysisCategories $analysisCategory): Response
    {
        if ($this->isCsrfTokenValid('delete'.$analysisCategory->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($analysisCategory);
            $entityManager->flush();
        }

        return $this->redirectToRoute('analysis_categories_index');
    }
}

templates/analysis_categories/_delete_form.html.twig
<form method="post" action="{{ path('analysis_categories_delete', {'id': analysis_category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ analysis_category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/analysis_categories/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/analysis_categories/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AnalysisCategories{% endblock %}

{% block body %}
    <h1>Edit AnalysisCategories</h1>

    {{ include('analysis_categories/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('analysis_categories_index') }}">back to list</a>

    {{ include('analysis_categories/_delete_form.html.twig') }}
{% endblock %}

templates/analysis_categories/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AnalysisCategories index{% endblock %}

{% block body %}
    <h1>AnalysisCategories index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Analysis_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for analysis_category in analysis_categories %}
            <tr>
                <td>{{ analysis_category.id }}</td>
                <td>{{ analysis_category.analysisName }}</td>
                <td>
                    <a href="{{ path('analysis_categories_show', {'id': analysis_category.id}) }}">show</a>
                    <a href="{{ path('analysis_categories_edit', {'id': analysis_category.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('analysis_categories_new') }}">Create new</a>
{% endblock %}

templates/analysis_categories/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AnalysisCategories{% endblock %}

{% block body %}
    <h1>Create new AnalysisCategories</h1>

    {{ include('analysis_categories/_form.html.twig') }}

    <a href="{{ path('analysis_categories_index') }}">back to list</a>
{% endblock %}

templates/analysis_categories/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AnalysisCategories{% endblock %}

{% block body %}
    <h1>AnalysisCategories</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ analysis_category.id }}</td>
            </tr>
            <tr>
                <th>Analysis_name</th>
                <td>{{ analysis_category.analysisName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('analysis_categories_index') }}">back to list</a>

    <a href="{{ path('analysis_categories_edit', {'id': analysis_category.id}) }}">edit</a>

    {{ include('analysis_categories/_delete_form.html.twig') }}
{% endblock %}